# []
# version = 1
# key = ""
# url = ""
# mmd = 86400

["Google 'Argon2025h2' log"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEr+TzlCzfpie1/rJhgxnIITojqKk9VK+8MZoc08HjtsLzD8e5yjsdeWVhIiWCVk6Y6KomKTYeKGBv6xVu93zQug=="
url = "https://ct.googleapis.com/logs/us1/argon2025h2/"
mmd = 86400

# TODO: Insert the Google Argon and Xenon logs

["Cloudflare 'Nimbus2025'"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGoAaFRkZI3m0+qB5jo3VwdzCtZaSfpTgw34UfAoNLUaonRuxQWUMX5jEWhd5gVtKFEHsr6ldDqsSGXHNQ++7lw=="
url = "https://ct.cloudflare.com/logs/nimbus2025/"
mmd = 86400

["Cloudflare 'Nimbus2026'"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2FxhT6xq0iCATopC9gStS9SxHHmOKTLeaVNZ661488Aq8tARXQV+6+jB0983v5FkRm4OJxPqu29GJ1iG70Ahow=="
url = "https://ct.cloudflare.com/logs/nimbus2026/"
mmd = 86400

["DigiCert Yeti2025 Log"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE35UAXhDBAfc34xB00f+yypDtMplfDDn+odETEazRs3OTIMITPEy1elKGhj3jlSR82JGYSDvw8N8h8bCBWlklQw=="
url = "https://yeti2025.ct.digicert.com/log/"
mmd = 86400

["DigiCert Nessie2025 Log"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8vDwp4uBLgk5O59C2jhEX7TM7Ta72EN/FklXhwR/pQE09+hoP7d4H2BmLWeadYC3U6eF1byrRwZV27XfiKFvOA=="
url = "https://nessie2025.ct.digicert.com/log/"
mmd = 86400

["DigiCert 'Wyvern2025h2' Log"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4NtB7+QEvctrLkzM8WzeQVh//pT2evZg7Yt2cqOiHDETMjWh8gjSaMU0p1YIHGPeleKBaZeNHqi3ZlEldU14Lg=="
url = "https://wyvern.ct.digicert.com/2025h2/"
mmd = 86400

# TODO: Insert DigiCert Logs for 2026

["DigiCert 'Sphinx2025h2' Log"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQYxQE1SxGQW3f0ogbqN1Y8o09Mx06jI7tosDFKhSfzKHXlmeD6sYnilstXJ3GidUhV3BeySoNOPNiM7UUBu+aQ=="
url = "https://sphinx.ct.digicert.com/2025h2/"
mmd = 86400


["Sectigo 'Sabre2025h2'"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhRMRLXvzk4HkuXzZZDvntYOZZnlZR2pCXta9Yy63kUuuvFbExW4JoNdkGsjBr4mL9VjYuut7g1Lp9OClzc2SzA=="
url = "https://sabre2025h2.ct.sectigo.com/"
mmd = 86400

["Sectigo 'Mammoth2025h2'"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiOLHs9c3o5HXs8XaB1EEK4HtwkQ7daDmZeFKuhuxnKkqhDEprh2L8TOfEi6QsRVnZqB8C1tif2yaajCbaAIWbw=="
url = "https://mammoth2025h2.ct.sectigo.com/"
mmd = 86400

["Sectigo 'Elephant2025h2'"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0OlLeGW2qUZGUoQERydw3GlayEO3ZK3418zThY1tDYr85ASme6ZOL/2DXyOXw8RCwVsKhRbOqMEOxW4Q2p4KQg=="
url = "https://elephant2025h2.ct.sectigo.com/"
mmd = 86400


["Let's Encrypt 'Oak2025h2'"]
version = 1
key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEtXYwB63GyNLkS9L1vqKNnP10+jrW+lldthxg090fY4eG40Xg1RvANWqrJ5GVydc9u8H3cYZp9LNfkAmqrr2NqQ=="
url = "https://oak.ct.letsencrypt.org/2025h2/"
mmd = 86400
